(define (domain robot-manipulation)
  (:requirements :strips :typing)
  (:types block container robot object)
  (:predicates
    (on ?x - block ?y - block)
    (on-table ?x - block)
    (in ?x - block ?c - container)
    (clear ?x - object)
    (holding ?r - robot ?x - block)
    (empty ?r - robot)
  )
  (:action pick-up
    :parameters (?r - robot ?x - block)
    :precondition (and (on-table ?x) (clear ?x) (empty ?r))
    :effect (and (holding ?r ?x) (not (on-table ?x)) (not (empty ?r)))
  )
  (:action put-down
    :parameters (?r - robot ?x - block)
    :precondition (holding ?r ?x)
    :effect (and (on-table ?x) (empty ?r) (not (holding ?r ?x)))
  )
  (:action stack
    :parameters (?r - robot ?x - block ?y - block)
    :precondition (and (holding ?r ?x) (clear ?y))
    :effect (and (on ?x ?y) (clear ?x) (empty ?r) (not (holding ?r ?x)) (not (clear ?y)))
  )
  (:action unstack
    :parameters (?r - robot ?x - block ?y - block)
    :precondition (and (on ?x ?y) (clear ?x) (empty ?r))
    :effect (and (holding ?r ?x) (clear ?y) (not (on ?x ?y)) (not (empty ?r)))
  )
  (:action put-in
    :parameters (?r - robot ?x - block ?c - container)
    :precondition (holding ?r ?x)
    :effect (and (in ?x ?c) (empty ?r) (not (holding ?r ?x)))
  )
  (:action take-out
    :parameters (?r - robot ?x - block ?c - container)
    :precondition (and (in ?x ?c) (empty ?r))
    :effect (and (holding ?r ?x) (not (in ?x ?c)) (not (empty ?r)))
  )
)